# Use NVIDIA Triton base image. Model repository is mounted at runtime.
FROM nvcr.io/nvidia/tritonserver:23.10-py3

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY --link model_repository/ /models/model_repository/

ENV TRITON_MODEL_REPOSITORY=/models/model_repository

EXPOSE 8000 8001 8002

CMD ["tritonserver", "--model-repository=/models/model_repository"]
